# Form implementation generated from reading ui file 'C:\Users\hayk.asatryan\Desktop\Haik\pythonprojects\eInvoiceToExcel\ui\DB_Window.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DBWindow(object):
    def setupUi(self, DBWindow):
        DBWindow.setObjectName("DBWindow")
        DBWindow.setEnabled(True)
        DBWindow.resize(460, 150)
        DBWindow.setMinimumSize(QtCore.QSize(460, 150))
        DBWindow.setMaximumSize(QtCore.QSize(460, 150))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hayk.asatryan\\Desktop\\Haik\\pythonprojects\\eInvoiceToExcel\\ui\\../Untergunter-Leaf-Mimes-Text-xml.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        DBWindow.setWindowIcon(icon)
        DBWindow.setStyleSheet("QMainWindow{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(166, 206, 57, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"font: 8pt \"Helvetica\";")
        self.centralwidget = QtWidgets.QWidget(DBWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.current_db_path = QtWidgets.QTextEdit(self.centralwidget)
        self.current_db_path.setEnabled(False)
        self.current_db_path.setGeometry(QtCore.QRect(110, 10, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.current_db_path.setFont(font)
        self.current_db_path.setObjectName("current_db_path")
        self.db_path = QtWidgets.QLineEdit(self.centralwidget)
        self.db_path.setEnabled(True)
        self.db_path.setGeometry(QtCore.QRect(20, 50, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.db_path.setFont(font)
        self.db_path.setObjectName("db_path")
        self.db_browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.db_browse_button.setGeometry(QtCore.QRect(360, 50, 91, 21))
        self.db_browse_button.setObjectName("db_browse_button")
        self.db_apply_button = QtWidgets.QPushButton(self.centralwidget)
        self.db_apply_button.setGeometry(QtCore.QRect(110, 90, 91, 21))
        self.db_apply_button.setObjectName("db_apply_button")
        self.db_window_close_button = QtWidgets.QPushButton(self.centralwidget)
        self.db_window_close_button.setGeometry(QtCore.QRect(270, 90, 91, 21))
        self.db_window_close_button.setObjectName("db_window_close_button")
        DBWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DBWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        DBWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DBWindow)
        self.statusbar.setObjectName("statusbar")
        DBWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DBWindow)
        QtCore.QMetaObject.connectSlotsByName(DBWindow)

    def retranslateUi(self, DBWindow):
        _translate = QtCore.QCoreApplication.translate
        DBWindow.setWindowTitle(_translate("DBWindow", "AS clients DB"))
        self.label.setText(_translate("DBWindow", "Ներկա ուղի"))
        self.db_browse_button.setText(_translate("DBWindow", "Փնտրել"))
        self.db_apply_button.setText(_translate("DBWindow", "Փոփոխել"))
        self.db_window_close_button.setText(_translate("DBWindow", "Դուրս գալ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DBWindow = QtWidgets.QMainWindow()
    ui = Ui_DBWindow()
    ui.setupUi(DBWindow)
    DBWindow.show()
    sys.exit(app.exec())
